@baseUrl = http://localhost:8000/api/v1

###
# регистрация нового пользователя
POST {{baseUrl}}/user/register
Content-Type: application/json

{
  "first_name": "Art",
  "last_name": "King",
  "email": "arturas.king@mail.ru",
  "password": "diplom123",
  "company": "UK",
  "position": "engineer"
}


###
# подтверждение почты через токен отправленный на почту
POST {{baseUrl}}/user/register/confirm
Content-Type: application/json

{
  "email": "arturas.king@mail.ru",
  "token": "900dc7c9a85dbfa32c"
}


###
# авторизация
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email": "arturas.king@mail.ru",
  "password": "diplom123"
}


###
# получение данных о пользователе
GET {{baseUrl}}/user/details
Authorization: Token e1cfdf5781e27c98261e90e08050c3fafceb3978


###
# редактирование данных о пользователе
POST {{baseUrl}}/user/details
Content-Type: application/json
Authorization: Token e1cfdf5781e27c98261e90e08050c3fafceb3978

{
  "first_name": "Stiven",
  "type": "shop"
}


###
# получение контактов пользователя
GET {{baseUrl}}/user/contact
Authorization: Token e1cfdf5781e27c98261e90e08050c3fafceb3978


###
# редактирование контактов пользователя
POST {{baseUrl}}/user/contact
Content-Type: application/json
Authorization: Token e1cfdf5781e27c98261e90e08050c3fafceb3978

{
  "city": "London",
  "street": "Bigstreet",
  "phone": "89210000001"
}


###
# загрузка товаров
POST {{baseUrl}}/partner/update
Content-Type: application/json
Authorization: Token e1cfdf5781e27c98261e90e08050c3fafceb3978

{
  "url": "urldata" 
}


###
# получение статуса работы магазина
GET {{baseUrl}}/partner/state
Authorization: Token e1cfdf5781e27c98261e90e08050c3fafceb3978


###
# посмотреть заказы для магазина
GET {{baseUrl}}/partner/orders
Authorization: Token e1cfdf5781e27c98261e90e08050c3fafceb3978


###
# получить все продукты
GET {{baseUrl}}/product
Content-Type: application/json


###
# добавить в корзину
POST {{baseUrl}}/basket
Content-Type: application/x-www-form-urlencoded
Authorization: Token 7a37486b0ab42ac81fc7da2038c97ad6196679b7

items=[
        {
        "product_info": 1,
        "quantity": 66
        },
        {
        "product_info": 2,
        "quantity": 99
        }
    ]


###
# посмотреть корзину
GET {{baseUrl}}/basket
Authorization: Token 7a37486b0ab42ac81fc7da2038c97ad6196679b7


###
# создать заказ из товаров в корзине
POST {{baseUrl}}/order
Content-Type: application/json
Authorization: Token 7a37486b0ab42ac81fc7da2038c97ad6196679b7

{
"id": "3",
"contact": "1"
}


###
# посмотреть заказы
GET {{baseUrl}}/order
Authorization: Token 7a37486b0ab42ac81fc7da2038c97ad6196679b7
