@baseUrl = http://localhost:8000/api/v1

###
# регистрация нового пользователя
POST {{baseUrl}}/user/register
Content-Type: application/json

{
  "first_name": "Art",
  "last_name": "King",
  "email": "arturas.king@mail.ru",
  "password": "diplom123",
  "company": "UK",
  "position": "engineer"
}


###
# подтверждение почты через токен отправленный на почту
POST {{baseUrl}}/user/register/confirm
Content-Type: application/json

{
  "email": "arturas.king@mail.ru",
  "token": "900dc7c9a85dbfa32c"
}


###
# авторизация
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email": "arturas.king@mail.ru",
  "password": "diplom123"
}


###
# получение данных о пользователе
GET {{baseUrl}}/user/details
Authorization: Token e1cfdf5781e27c98261e90e08050c3fafceb3978


###
# редактирование данных о пользователе
POST {{baseUrl}}/user/details
Content-Type: application/json
Authorization: Token e1cfdf5781e27c98261e90e08050c3fafceb3978

{
  "first_name": "Stiven"
}


###
# получение статуса
GET {{baseUrl}}/partner/state
Authorization: Token e1cfdf5781e27c98261e90e08050c3fafceb3978




###
# загрузка товаров
POST {{baseUrl}}/partner/update
Content-Type: application/json
Authorization: Token e1cfdf5781e27c98261e90e08050c3fafceb3978

{
  "url": "urldata" 
}





###
# обновление продукта
PATCH {{baseUrl}}/product/1/
Content-Type: application/json
в
{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/1/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=помидор
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "мой адрес не дом и не улица, мой адрес сегодня такой: www.ленинград-спб.ru3",
  "positions": [
    {
      "product": 2,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 3,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/4/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 100,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 243,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=2
Content-Type: application/json
